---
title: "Memo 3"
author: "Maliat"
date: "9/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("C:/Users/malia/OneDrive/Desktop/710 Memos")
library(tidyverse)
library(magrittr)
library(foreign)
library(descr)
library(lubridate)
```



```{r}
table(GSS$happy)
  

table(GSS$marital)
```

```{r}
table(GSS$marital, GSS$happy)
```

```{r}
prop.table(table(GSS$marital, GSS$happy), 1) 
```

```{r}
chisq.test(GSS$marital, GSS$happy) 
```

```{r}
table(GSS$letin)
```

```{r}
prop.table(table(GSS$race,GSS$letin,GSS$educ),1)
```
```{r}
chisq.test(GSS$race,GSS$letin)
```

```{r}
library(expss)
```
```{r}

crosstab(GSS$race, GSS$letin, prop.r = T, chisq = T, dnn=c("Race", "Immigration")) 
```
```{r}
prop.table(table(GSS$race,GSS$helpblk),1)
chisq.test(GSS$race,GSS$letin)
```

```{r}
table(GSS$letin,GSS$race)
  
```

```{r}
table(GSS$letin,GSS$educ<12)
```

```{r}
crosstab(GSS$educ>12, GSS$letin, prop.r = T, chisq = T, dnn=c("Race", "Immigration"))
crosstab(GSS$educ<12, GSS$letin, prop.r = T, chisq = T, dnn=c("Race", "Immigration")) 
crosstab(GSS$educ==12, GSS$letin, prop.r = T, chisq = T, dnn=c("Race", "Immigration")) 
```



```{r}

GSS$socclass<- cut(GSS$educ, c(0,11,12,99), labels=c("high school dropout","highschool graduate","at least some college"))

```


```{r}
GSS.1 <- GSS %>%
  select(year,socclass,letin)%>%
  filter(year %in% c("2000","2002","2004","2006","2008","2010","2012","2014"))
  crosstab(GSS.1$socclass, GSS.1$letin, prop.r = T, chisq = T, dnn=c("Social Class", "Immigration Views"))
```
```{r}
GSS.1 <- GSS %>%
  select(year,race,letin)%>%
  filter(year %in% c("2000","2002","2004","2006","2008","2010","2012","2014"))
  crosstab(GSS.1$race, GSS.1$letin, prop.r = T, chisq = T, dnn=c("Race", "Immigration Views"))
```

```{r}
GSS.1 <- GSS %>%
  select(year,socclass,polviews)%>%
  filter(year %in% c("2000","2002","2004","2006","2008","2010","2012","2014"))
  crosstab(GSS.1$socclass, GSS.1$polviews, prop.r = T, chisq = T, dnn=c("Social Class", "Political Views"))
```
```{r}
freq(GSS$polviews)
```

```{r}
GSS.1 <- GSS %>%
  select(year,race,polviews)%>%
  filter(year %in% c("2000","2002","2004","2006","2008","2010","2012","2014"))
  crosstab(GSS.1$race, GSS.1$polviews, prop.r = T, chisq = T, dnn=c("Race", "Political Views"))
```

```{r}
GSS.1 <- GSS %>%
  select(year,socclass,helpblk)%>%
  filter(year %in% c("2000","2002","2004","2006","2008","2010","2012","2014"))
  crosstab(GSS.1$socclass, GSS.1$helpblk, prop.r = T, chisq = T, dnn=c("Social Class", "government intervention in helping black people "))
```

```{r}
GSS.1 <- GSS %>%
  select(year,socclass,abany)%>%
  filter(year %in% c("2000","2002","2004","2006","2008","2010","2012","2014"))
  crosstab(GSS.1$socclass, GSS.1$abany, prop.r = T, chisq = T, dnn=c("Social Class", "views on abortion "))
```


```{r}
GSS.1 <- GSS %>%
  select(year,race,abany)%>%
  filter(year %in% c("2000","2002","2004","2006","2008","2010","2012","2014"))
  crosstab(GSS.1$race, GSS.1$abany, prop.r = T, chisq = T, dnn=c("race", "views on abortion "))

```

```{r}
GSS.1 <- GSS %>%
  select(year,race,racdif1)%>%
  filter(year %in% c("2000","2002","2004","2006","2008","2010","2012","2014"))
  crosstab(GSS.1$race, GSS.1$racdif1, prop.r = T, chisq = T, dnn=c("race", "views on African American's income inequality due to discrimination"))

  
```

```{r}
freq(GSS$racdif1)
```



